name: repolinter
on: [push, pull_request]

jobs:
  repolinter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: willnorris/repolinter-action@getconfig
      with:
        config_file: .github/repolinter.yaml
